### ISSUE TITLE
Tests are failing after upgrade to Tags::HTML::Page::Begin 0.15

### ISSUE THREAD

**Issue by andk** [michal-josef-spacek/Plack-App-Login#1]
One of my smokers just sent a pass report, then upgraded to Tags::HTML::Page::Begin 0.15, then tested again and sent a fail report:

- the pass: http://www.cpantesters.org/cpan/report/fc9cf198-a934-11ed-be0f-156b72f12ea7
- the fail:  http://www.cpantesters.org/cpan/report/1b7d2088-a935-11ed-97fd-6a6c72f12ea7

**Comment by michal-josef-spacek** [comment]
Fixed in Plack::App::Login@0.07
